apiVersion: v1
kind: Service
metadata:
  name: azurite-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: azurite
  ports:
    - name: blob
      protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 30080
    - name: queue
      protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30081
    - name: table
      protocol: TCP
      port: 10002
      targetPort: 10002
      nodePort: 30082