apiVersion: v1
kind: Service
metadata:
  name: {{ include "azurite.fullname" . }}
  labels:
    {{- include "azurite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.porta }}
      protocol: TCP
      name: porta
    - port: {{ .Values.service.portb }}
      protocol: TCP
      name: portb
    - port: {{ .Values.service.portc }}
      protocol: TCP
      name: portc
  selector:
    {{- include "azurite.selectorLabels" . | nindent 4 }}
